### PR TITLE
Fix slack workspace link

### PR DESCRIPTION
**Pull request by aNeutrino**
Special link was generated which allows people
 to be automatically invited to workspace.

### CODE REVIEW

**Comment by uristdwarf** [comment]
The CONTRIBUTING.md also has a slack link.

**Comment by uristdwarf** [comment]
Also it should be merged into main as a hotfix, since most people will see that. We can later merge it into dev

**Review by ralcolea — APPROVED** [review]
Nice!! :+1:

**Review by ictus4u — APPROVED** [review]

**Comment by uristdwarf** [comment]
Main needs to be merged to dev before merging this

**Pull request merged**
