### PR TITLE
cgi: Update sfs.css

### PR DESCRIPTION
**Pull request by ss-leil**
CSS improvements for the monitoring.

### CODE REVIEW

**Comment by dmga44** [comment]
Maybe not relevant @ss-leil , but could you use our commit message format? Your commit message should probably look like this: "cgi: Update file sfs.css web interface".

I think this change has nothing to do with CI and we could merge it even before CI works again.

**Comment by uristdwarf** [comment]
It's good, but as @dmga44 mentioned, please format your PR title to something like `cgi: Update sfs.css`. While someone can do it later when merging, it's good practice.

> I think this change has nothing to do with CI (only changes colors) and we could merge it even before CI works again.

Repository settings do not allow merging when CI doesn't pass and while I could force it through, it's best to wait until it works again unless it's really urgent.

**Review by uristdwarf — APPROVED** [review]

**Review by lgsilva3087 — CHANGES_REQUESTED** [review]
The PR is pointing to main, it should be dev.

**Comment by lgsilva3087** [comment]
I changed the target to dev.

**Review by lgsilva3087 — APPROVED** [review]

**Pull request merged**
