### PR TITLE
cgi: Add png version of logo

### PR DESCRIPTION
**Pull request by aNeutrino**

### CODE REVIEW

**Review by lgsilva3087 — APPROVED** [review]
LGTM.

**Comment by ar-leil** [comment]
@aNeutrino just in case - all branding files for all sites (Leil and Sauna) can be accessed at website_name/branding

It will download an archive with proper versions in different formats. Please use this rather some anything else.

**Review by ralcolea — APPROVED** [review]
LGTM.

**Comment by aNeutrino** [comment]
> @aNeutrino just in case - all branding files for all sites (Leil and Sauna) can be accessed at website_name/branding
> 
> It will download an archive with proper versions in different formats. Please use this rather some anything else.

Thanks @ar-leil I have updated image with our official version: https://github.com/leil-io/saunafs/pull/124/commits/3cee573db29b6f3a70dfda931d8aad100b9238eb

it is going to be used in our TERMINALS converted to ASCII ART:
image

**Pull request merged**
